export const ProductsData = [
  {
    id: "1",
    category: "本日精選",
    imgUrl: "https://bit.ly/2zBjQuq",
    name: "美味甜甜圈",
    price: "$250",
  },
  {
    id: "2",
    category: "人氣推薦",
    imgUrl: "https://bit.ly/2zBDAxX",
    name: "櫻桃三明治",
    price: "$300",
  },
  {
    id: "3",
    category: "新品上市",
    imgUrl: "https://bit.ly/2QbVsVR",
    name: "藍莓奶酪",
    price: "$450",
  },
  {
    id: "4",
    category: "本日精選",
    imgUrl: "https://bit.ly/2zBjQuq",
    name: "美味甜甜圈",
    price: "$250",
  },
  {
    id: "5",
    category: "人氣推薦",
    imgUrl: "https://bit.ly/2zBDAxX",
    name: "櫻桃三明治",
    price: "$300",
  },
  {
    id: "6",
    category: "新品上市",
    imgUrl: "https://bit.ly/2QbVsVR",
    name: "藍莓奶酪",
    price: "$450",
  },
  {
    id: "7",
    category: "人氣推薦",
    imgUrl: "https://bit.ly/2zBDAxX",
    name: "櫻桃三明治",
    price: "$300",
  },
  {
    id: "8",
    category: "新品上市",
    imgUrl: "https://bit.ly/2QbVsVR",
    name: "藍莓奶酪",
    price: "$450",
  },
];
